### ISSUE TITLE
Security for Database

### ISSUE THREAD

**Issue by AurumTheEnd** [sybila/biodivine-boolean-models-website#45]
It probably isn't for the best that the postgres passwords are just laying in plaintext in the compose file and the CI docker build.

The compose file should use .env and the CI should use repo secret variables.

**Comment by daemontus** [comment]
Technically yes. Practically... if the database is deployed correctly, it won't matter :)

I think the real problem is that `./backend/docker-compose.yml` is very much not the recommended way of running this in production. (i.e. the repository does not actually contain the recommended docker compose file)

In the production setting, that database container should only be accessible using a private docker sub-network, so the only other process that can access it is the `backend` container. In other words, to compromise the database using the published passwords, I must either have (a) root access to the host machine where the container is running to access the private sub-network or (b) gain remote code execution in the `backend` container. In both cases, I can extract the database password easily from configuration (i.e. if (a) or (b) happens, I'm screwed regardless of the password setting).

This is the current production `docker-compose.yml`:

```
name: bbm-website

services:
  bbm-database:
    image: daemontus/bbm-database:latest
    container_name: bbm-database
    restart: 'always'
    networks:
      - bbm-net
    environment:
      PGDATA: '/data'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'

  bbm-backend:
    image: daemontus/bbm-backend:latest
    container_name: bbm-backend
    restart: 'always'
    ports:
      - '14000:3000'
    networks:
      - bbm-net
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@bbm-database:5432/postgres'

  bbm-frontend:
    image: daemontus/bbm-frontend:latest
    container_name: bbm-frontend
    restart: 'always'
    ports:
      - '14001:80'
    environment:
      BACKEND_URL: 'https://bbm.sybila.fi.muni.cz/api'

networks:
  bbm-net:

```

Notice that `bbm-database` does not expose any ports, and `bbm-backend` accesses the `bbm-database` container directly.

*With that said...* in general, not everyone wants to (or can) deploy custom docker networks to create private connections between containers. So adding actual secure passwords would allow safe deployment without docker sub-networks.

*Also also...* if we actually use a secure password to seed the database, it means no one else can use the pre-seeded docker image that we publish, unless we also publish the password. This is not necessarily bad, but it's up for debate (i.e. do we allow / encourage reuse of the database image, or is it just for internal use).
